### PR TITLE
embrace MonadFail, support ghc-9.0.1

### PR DESCRIPTION
**Pull request by gelisam**
Replaces #250.

### CODE REVIEW

**Comment by juhp** [comment]
Seems some Template Haskell issue

**Comment by gelisam** [comment]
ghc-9.0.1 is using template-haskell-0.17.0.0, which isn't on hackage yet, but its documentation can be found [on the ghc gitlab](https://ghc.gitlab.haskell.org/ghc/doc/libraries/template-haskell-2.17.0.0/Language-Haskell-TH-Syntax.html#t:Code). Looks like typed template haskell now produces `Code Q a`, a newtype wrapper around `Q (TExp a)`, instead of returning a `Q (TExp a)` directly. Thus, a `Code` constructor must be added to both `compileTimeEnvVar` and `compileTimeWorkingDirectory`. I guess it's time to add CPP!

**Comment by juhp** [comment]
Yay
(I don't really use TH myself, but I hear it tends to break between major releases?)

**Comment by gelisam** [comment]
I don't remember TH causing me issues with backwards-compatible changes, it's mostly haskell-src-exts which has been causing me pain in the past. It would make sense for both of them to change their AST representation whenever ghc adds a new syntactic feature. However, with TH, I'm rarely pattern-matching on the resulting AST, so those changes are less likely to cause me problems.

**Comment by juhp** [comment]
Cool

Any chance of a new release?

**Comment by gelisam** [comment]
Sure; shall we do that together when we pair on Friday, or do you need it before that?

**Pull request merged**
